### ISSUE TITLE
可以微信交流一下吗

### ISSUE THREAD

**Issue by wjsvec** [yuluo-yx/yuluo-yx#1]
嗨，我在寒假想做一些参与开源的同学的访谈视频，类似下面这样的形式

https://www.bilibili.com/video/BV1sP411X7uw/?spm_id_from=333.999.0.0

有兴趣来聊聊天吗~😉我的微信已经发送到你的邮箱啦

**Comment by yuluo-yx** [comment]
当然可以，我刚才加了您的微信 😆😆
